--계정생성
--DROP USER c##tester1 CASCADE;
--CREATE USER c##tester1 IDENTIFIED BY 1234 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
--GRANT CONNECT, RESOURCE TO c##tester1; 
--GRANT CREATE VIEW, CREATE SYNONYM TO c##tester1; 
--GRANT UNLIMITED TABLESPACE TO c##tester1; 
--ALTER USER c##tester1 ACCOUNT UNLOCK;

DROP USER c##HOMECABE CASCADE;
--계정생성
CREATE USER c##HOMECABE IDENTIFIED BY 1234 
    DEFAULT TABLESPACE users 
    TEMPORARY TABLESPACE temp 
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##HOMECABE; 
GRANT CREATE VIEW, CREATE SYNONYM TO c##HOMECABE; 
GRANT UNLIMITED TABLESPACE TO c##HOMECABE;
--락 풀기
ALTER USER c##HOMECABE ACCOUNT UNLOCK;